<a href="https://colab.research.google.com/github/anjha1/Data-Science/blob/main/Python/147.%20Logistic%20Regression%20Implementation/Logistic_Regression_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from sklearn.datasets import load_iris

In [6]:
dataset=load_iris()

In [7]:
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [10]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [11]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [13]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [15]:
df['target']=dataset.target

In [17]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
0                5.1               3.5                1.4               0.2       0
1                4.9               3.0                1.4               0.2       0
2                4.7               3.2                1.3               0.2       0
3                4.6               3.1                1.5               0.2       0
4                5.0               3.6                1.4               0.2       0

In [20]:
dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [19]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

#Binary Classification

In [23]:
df_copy=df[df['target']!=2]

In [24]:
df_copy.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
0                5.1               3.5                1.4               0.2       0
1                4.9               3.0                1.4               0.2       0
2                4.7               3.2                1.3               0.2       0
3                4.6               3.1                1.5               0.2       0
4                5.0               3.6                1.4               0.2       0

In [26]:
df_copy['target'].value_counts()

target
0    50
1    50
Name: count, dtype: int64

# independent and dependent feature

In [36]:
X=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

#train test split

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [38]:
classifier=LogisticRegression()
classifier.fit(X_train,y_train)

LogisticRegression()

#Prediction

In [47]:
classifier.predict_proba(X_test)

array([[0.96348831, 0.03651169],
       [0.00385659, 0.99614341],
       [0.98328342, 0.01671658],
       [0.0084173 , 0.9915827 ],
       [0.0078275 , 0.9921725 ],
       [0.12191246, 0.87808754],
       [0.98516937, 0.01483063],
       [0.00504168, 0.99495832],
       [0.00404878, 0.99595122],
       [0.02097114, 0.97902886],
       [0.01788804, 0.98211196],
       [0.02225599, 0.97774401],
       [0.0067456 , 0.9932544 ],
       [0.99009052, 0.00990948],
       [0.97535089, 0.02464911],
       [0.96389415, 0.03610585],
       [0.99405714, 0.00594286],
       [0.94665395, 0.05334605],
       [0.98753933, 0.01246067],
       [0.97639386, 0.02360614]])

In [39]:
y_pred=classifier.predict(X_test)

In [40]:
y_pred

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0])

## Confusion matrix, accuracy score, classification report


In [43]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm=confusion_matrix(y_test,y_pred)
cm

array([[10,  0],
       [ 0, 10]])

In [44]:
accuracy_score(y_test,y_pred)

1.0

In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



#Hyperparameter Tuning


## Gridsearchcv


In [49]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [50]:
# Defining parameter grid
parameters = {
    'penalty': ['l1', 'l2', 'elasticnet'],  # Corrected invalid values
    'C': [1, 10, 20]
}

# Creating GridSearchCV instance
clf = GridSearchCV(estimator=classifier, param_grid=parameters, cv=5)

# Splitting training data to validation data
clf.fit(X_train, y_train)


GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ['l1', 'l2', 'elasticnet']})

In [51]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [52]:
classifier=LogisticRegression(C=1,penalty='l2')
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [53]:
y_pred=classifier.predict(X_test)

In [54]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[10,  0],
       [ 0, 10]])

In [55]:
accuracy_score(y_test,y_pred)

1.0

In [56]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [57]:
# Importing required libraries
from sklearn.model_selection import RandomizedSearchCV


# Creating RandomizedSearchCV instance
random_clf = RandomizedSearchCV(
    estimator=LogisticRegression(),
    param_distributions=parameters,
    cv=5
)

# Fitting the model
random_clf.fit(X_train, y_train)

# Displaying best parameters
random_clf.best_params_


{'penalty': 'l2', 'C': 1}

In [58]:
classifier=LogisticRegression(C=1,penalty='l2')
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [59]:
y_pred=classifier.predict(X_test)

In [60]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[10,  0],
       [ 0, 10]])

In [61]:
accuracy_score(y_test,y_pred)

1.0

In [62]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

