<a href="https://colab.research.google.com/github/anjha1/Data-Science/blob/main/Python/51.%20Numpy%20Part-1/class51_Numpy_Part_1_by_anjha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
l=[1,2,3,4,5]

In [ ]:
ar=np.array(l)

In [ ]:
ar

array([1, 2, 3, 4, 5])

In [ ]:
type(ar)

numpy.ndarray

In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [10]:
a=[1,2,3]

In [11]:
np.asanyarray(a)

array([1, 2, 3])

In [12]:
b=np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4, 5]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4, 5]])

In [16]:
a=np.array(l)

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
c=a

In [19]:
c

array([1, 2, 3, 4, 5])

In [20]:
a

array([1, 2, 3, 4, 5])

In [21]:
c[0]=100

In [22]:
c

array([100,   2,   3,   4,   5])

In [23]:
a

array([100,   2,   3,   4,   5])

In [24]:
d=np.copy(a)

In [25]:
d

array([100,   2,   3,   4,   5])

In [26]:
a[1]=400

In [27]:
a

array([100, 400,   3,   4,   5])

In [28]:
d

array([100,   2,   3,   4,   5])

In [29]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i,j:i<=j,(3,3))  #upper triangular

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j:i>=j,(3,3))  #lower triangular

array([[ True, False, False],
       [ True,  True, False],
       [ True,  True,  True]])

In [30]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
iterable=(i*i for i in range(5))

In [35]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [36]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [37]:
np.fromstring('4,5',sep=',')

array([4., 5.])

### **NumPy Data Type**

In [38]:
l=[1,2,3,4,5,6]

In [39]:
arr=np.array(l)

In [40]:
arr

array([1, 2, 3, 4, 5, 6])

In [41]:
arr.ndim

1

In [45]:
arr2=np.array([[1,2,3,4],[2,3,4,5]])

In [46]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [47]:
arr2.ndim

2

In [48]:
arr2.size

8

In [49]:
ar

array([1, 2, 3, 4, 5])

In [50]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [51]:
ar.shape

(5,)

In [52]:
arr2.shape

(2, 4)

In [55]:
ar.dtype

dtype('int64')

In [56]:
arr2.dtype

dtype('int64')

In [57]:
ar22=np.array([[1.5,45,45],[23,45,56]])

In [58]:
ar22

array([[ 1.5, 45. , 45. ],
       [23. , 45. , 56. ]])

In [59]:
ar22.dtype

dtype('float64')

In [60]:
list(range(0,5))  #range function

[0, 1, 2, 3, 4]

In [61]:
list(range(0,5,0.3))

TypeError: 'float' object cannot be interpreted as an integer

In [65]:
np.arange(2.3,5.6,0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [64]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [67]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [68]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [69]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
arr4=np.zeros((3,4,2))  #3*4*2

In [72]:
arr4

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [73]:
arr4.ndim

3

In [74]:
arr4

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [75]:
np.ones(4)

array([1., 1., 1., 1.])

In [76]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
on=np.ones((2,3,2))
on

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [80]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [81]:
on*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [82]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [83]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [85]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [86]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [90]:
arr=np.random.randn(3,4)
arr

array([[ 0.21418058,  0.78704999,  0.72815291,  0.8004616 ],
       [-0.68546194, -0.10552343,  0.12499671,  1.48853984],
       [ 0.36181149, -1.24073573, -1.74003095, -1.52772121]])

In [91]:
import pandas as pd

In [92]:
pd.DataFrame(arr)

0         1         2         3
0  0.214181  0.787050  0.728153  0.800462
1 -0.685462 -0.105523  0.124997  1.488540
2  0.361811 -1.240736 -1.740031 -1.527721

In [93]:
np.random.rand(3,4)

array([[0.42820244, 0.50348684, 0.87672089, 0.85102629],
       [0.67774795, 0.05082004, 0.77354489, 0.78940485],
       [0.4806845 , 0.52095634, 0.50319134, 0.08413717]])

In [94]:
np.random.randint(1,110,(3,4))

array([[107,  18,  58,  99],
       [  7,  15,  38,  53],
       [ 20,  73,  18,  94]])

In [95]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [97]:
arr=np.random.rand(3,4)
arr

array([[0.64878417, 0.07037717, 0.14228716, 0.18531811],
       [0.15059683, 0.26018932, 0.13073212, 0.55507705],
       [0.29097494, 0.22779034, 0.80734707, 0.96774532]])

In [99]:
arr.reshape(6,2)

array([[0.64878417, 0.07037717],
       [0.14228716, 0.18531811],
       [0.15059683, 0.26018932],
       [0.13073212, 0.55507705],
       [0.29097494, 0.22779034],
       [0.80734707, 0.96774532]])

In [103]:
arr.reshape(6,-1)

array([[0.64878417, 0.07037717],
       [0.14228716, 0.18531811],
       [0.15059683, 0.26018932],
       [0.13073212, 0.55507705],
       [0.29097494, 0.22779034],
       [0.80734707, 0.96774532]])

In [107]:
arr1=arr.reshape(6,-189798787867)
arr1

array([[0.64878417, 0.07037717],
       [0.14228716, 0.18531811],
       [0.15059683, 0.26018932],
       [0.13073212, 0.55507705],
       [0.29097494, 0.22779034],
       [0.80734707, 0.96774532]])

In [108]:
arr1[2][1]

0.2601893201691253

In [109]:
arr1[2,1]

0.2601893201691253

In [111]:
arr1[2:4,0:2]

array([[0.15059683, 0.26018932],
       [0.13073212, 0.55507705]])

In [112]:
arr1[2:4,[0,1]]

array([[0.15059683, 0.26018932],
       [0.13073212, 0.55507705]])

In [114]:
arr1[[2,3]]

array([[0.15059683, 0.26018932],
       [0.13073212, 0.55507705]])

In [115]:
arr1[[2,3],[0,1]]

array([0.15059683, 0.55507705])

In [116]:
arr1

array([[0.64878417, 0.07037717],
       [0.14228716, 0.18531811],
       [0.15059683, 0.26018932],
       [0.13073212, 0.55507705],
       [0.29097494, 0.22779034],
       [0.80734707, 0.96774532]])

In [118]:
arr2=np.random.rand(5,5,4)
arr2

array([[[0.56508991, 0.50564859, 0.57595538, 0.09269663],
        [0.65679456, 0.12356765, 0.64152337, 0.65546564],
        [0.8540287 , 0.29722105, 0.03208735, 0.14747828],
        [0.84976348, 0.23666846, 0.38473871, 0.51340086],
        [0.22482975, 0.5839601 , 0.31398544, 0.85823819]],

       [[0.80432008, 0.22798298, 0.13357541, 0.92827078],
        [0.21402785, 0.42314104, 0.876397  , 0.76991554],
        [0.89147513, 0.16473318, 0.29606629, 0.93382122],
        [0.4345306 , 0.11009982, 0.96884624, 0.42970149],
        [0.42736275, 0.99472292, 0.42929498, 0.13210967]],

       [[0.38615078, 0.36083683, 0.70742058, 0.32329348],
        [0.13874785, 0.08179741, 0.93698228, 0.2083039 ],
        [0.48145728, 0.12967838, 0.47707055, 0.38007965],
        [0.81853663, 0.68975011, 0.37951148, 0.37899593],
        [0.02515923, 0.93702409, 0.98746283, 0.0874116 ]],

       [[0.14696003, 0.40723945, 0.94851611, 0.61199355],
        [0.78856932, 0.19090989, 0.95680183, 0.41859978],
        

In [119]:
arr2[1,1:4,0:5]

array([[0.21402785, 0.42314104, 0.876397  , 0.76991554],
       [0.89147513, 0.16473318, 0.29606629, 0.93382122],
       [0.4345306 , 0.11009982, 0.96884624, 0.42970149]])

In [122]:
arr2[1,1:4,]

array([[0.21402785, 0.42314104, 0.876397  , 0.76991554],
       [0.89147513, 0.16473318, 0.29606629, 0.93382122],
       [0.4345306 , 0.11009982, 0.96884624, 0.42970149]])

In [124]:
arr2[1,[1,2,3]]

array([[0.21402785, 0.42314104, 0.876397  , 0.76991554],
       [0.89147513, 0.16473318, 0.29606629, 0.93382122],
       [0.4345306 , 0.11009982, 0.96884624, 0.42970149]])

In [128]:
arr2[1,[1,2,3],[0,1,3]] # digonal

array([0.21402785, 0.16473318, 0.42970149])

In [132]:
arr=np.random.randint(1,100,(5,5 ))
arr

array([[ 8, 67, 46, 31, 84],
       [69, 43, 34, 22, 29],
       [67, 72, 81, 38, 62],
       [25, 62, 58, 69, 47],
       [ 3, 79,  2, 95, 13]])

In [133]:
arr>50

array([[False,  True, False, False,  True],
       [ True, False, False, False, False],
       [ True,  True,  True, False,  True],
       [False,  True,  True,  True, False],
       [False,  True, False,  True, False]])

In [134]:
arr[arr>50]

array([67, 84, 69, 67, 72, 81, 62, 62, 58, 69, 79, 95])

In [135]:
arr

array([[ 8, 67, 46, 31, 84],
       [69, 43, 34, 22, 29],
       [67, 72, 81, 38, 62],
       [25, 62, 58, 69, 47],
       [ 3, 79,  2, 95, 13]])

In [136]:
arr[2:4,[1,2]]

array([[72, 81],
       [62, 58]])

In [137]:
arr[0][0]=500

In [138]:
arr

array([[500,  67,  46,  31,  84],
       [ 69,  43,  34,  22,  29],
       [ 67,  72,  81,  38,  62],
       [ 25,  62,  58,  69,  47],
       [  3,  79,   2,  95,  13]])

In [139]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [140]:
arr1

array([[1, 1, 1],
       [2, 1, 2],
       [2, 1, 1]])

In [141]:
arr2

array([[1, 1, 1],
       [2, 1, 1],
       [1, 2, 1]])

In [142]:
arr1+arr2

array([[2, 2, 2],
       [4, 2, 3],
       [3, 3, 2]])

In [143]:
arr1-arr2

array([[ 0,  0,  0],
       [ 0,  0,  1],
       [ 1, -1,  0]])

In [144]:
arr1*arr2

array([[1, 1, 1],
       [4, 1, 2],
       [2, 2, 1]])

In [145]:
arr1/arr2

array([[1. , 1. , 1. ],
       [1. , 1. , 2. ],
       [2. , 0.5, 1. ]])

In [147]:
arr1,arr2

(array([[1, 1, 1],
        [2, 1, 2],
        [2, 1, 1]]),
 array([[1, 1, 1],
        [2, 1, 1],
        [1, 2, 1]]))

In [146]:
arr1@arr2

array([[4, 4, 3],
       [6, 7, 5],
       [5, 5, 4]])

In [148]:
arr1/0

<ipython-input-148-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [149]:
arr1+100

array([[101, 101, 101],
       [102, 101, 102],
       [102, 101, 101]])

In [150]:
arr1**2

array([[1, 1, 1],
       [4, 1, 4],
       [4, 1, 1]])

### **Numpy Broadcasting**

In [152]:
arr=np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [154]:
row=np.array([1,2,3,4])
row

array([1, 2, 3, 4])

In [155]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [156]:
row.T

array([1, 2, 3, 4])

In [157]:
col=np.array([[1,2,3,4]])
col

array([[1, 2, 3, 4]])

In [158]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [159]:
col.T+arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [160]:
arr1=np.random.randint(1,4,(3,4))
arr1

array([[1, 3, 1, 1],
       [2, 3, 1, 1],
       [1, 2, 2, 2]])

In [161]:
np.sqrt(arr1)

array([[1.        , 1.73205081, 1.        , 1.        ],
       [1.41421356, 1.73205081, 1.        , 1.        ],
       [1.        , 1.41421356, 1.41421356, 1.41421356]])

In [162]:
np.exp(arr1)

array([[ 2.71828183, 20.08553692,  2.71828183,  2.71828183],
       [ 7.3890561 , 20.08553692,  2.71828183,  2.71828183],
       [ 2.71828183,  7.3890561 ,  7.3890561 ,  7.3890561 ]])

In [165]:
np.log(arr1)

array([[0.        , 1.09861229, 0.        , 0.        ],
       [0.69314718, 1.09861229, 0.        , 0.        ],
       [0.        , 0.69314718, 0.69314718, 0.69314718]])

In [164]:
np.log10(arr1)

array([[0.        , 0.47712125, 0.        , 0.        ],
       [0.30103   , 0.47712125, 0.        , 0.        ],
       [0.        , 0.30103   , 0.30103   , 0.30103   ]])