<a href="https://colab.research.google.com/github/anjha1/Data-Science/blob/main/Python/52.%20Numpy%20part-2/class52_Numpy_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **NumPy Array Manipulation**

In [133]:
import numpy as np

In [134]:
arr=np.random.randint(1,10,(3,4))
arr

array([[5, 3, 4, 2],
       [3, 7, 4, 1],
       [8, 5, 4, 1]])

In [135]:
arr.reshape(2,6)

array([[5, 3, 4, 2, 3, 7],
       [4, 1, 8, 5, 4, 1]])

In [136]:
arr.reshape(6,-1)

array([[5, 3],
       [4, 2],
       [3, 7],
       [4, 1],
       [8, 5],
       [4, 1]])

In [137]:
arr.reshape(6,-188888)

array([[5, 3],
       [4, 2],
       [3, 7],
       [4, 1],
       [8, 5],
       [4, 1]])

In [138]:
arr.T

array([[5, 3, 8],
       [3, 7, 5],
       [4, 4, 4],
       [2, 1, 1]])

In [139]:
arr

array([[5, 3, 4, 2],
       [3, 7, 4, 1],
       [8, 5, 4, 1]])

In [140]:
arr.flatten()

array([5, 3, 4, 2, 3, 7, 4, 1, 8, 5, 4, 1])

In [141]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [142]:
arr1.ndim

1

In [143]:
arr1

array([1, 2, 3, 4, 5])

In [144]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [145]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4, 5]])

In [146]:
arr

array([[5, 3, 4, 2],
       [3, 7, 4, 1],
       [8, 5, 4, 1]])

In [147]:
arr.squeeze()

array([[5, 3, 4, 2],
       [3, 7, 4, 1],
       [8, 5, 4, 1]])

In [148]:
data=np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [149]:
data1=np.array([[1,2],[2,2],[3,7]])
data1

array([[1, 2],
       [2, 2],
       [3, 7]])

In [150]:
np.squeeze(data)

array([1, 2, 3])

In [151]:
np.squeeze(data1)

array([[1, 2],
       [2, 2],
       [3, 7]])

In [152]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [153]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [154]:
arr1.repeat(3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [155]:
np.roll(arr1,2)

array([3, 4, 1, 2])

In [156]:
np.roll(arr1,3)

array([2, 3, 4, 1])

In [157]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### **NumPy Binary Operators**

In [158]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [159]:
arr1

array([[8, 2, 1, 6],
       [5, 9, 1, 8],
       [4, 3, 8, 7]])

In [160]:
arr2

array([[8, 2, 7, 7],
       [6, 8, 5, 7],
       [8, 9, 7, 3]])

In [161]:
arr1+arr2

array([[16,  4,  8, 13],
       [11, 17,  6, 15],
       [12, 12, 15, 10]])

In [162]:
arr1*arr2

array([[64,  4,  7, 42],
       [30, 72,  5, 56],
       [32, 27, 56, 21]])

In [163]:
arr1/arr2

array([[1.        , 1.        , 0.14285714, 0.85714286],
       [0.83333333, 1.125     , 0.2       , 1.14285714],
       [0.5       , 0.33333333, 1.14285714, 2.33333333]])

In [164]:
arr1-arr2


array([[ 0,  0, -6, -1],
       [-1,  1, -4,  1],
       [-4, -6,  1,  4]])

In [165]:
arr1%arr2

array([[0, 0, 1, 6],
       [5, 1, 1, 1],
       [4, 3, 1, 1]])

In [166]:
arr1**arr2

array([[16777216,        4,        1,   279936],
       [   15625, 43046721,        1,  2097152],
       [   65536,    19683,  2097152,      343]])

In [167]:
arr1&arr2

array([[8, 2, 1, 6],
       [4, 8, 1, 0],
       [0, 1, 0, 3]])

In [168]:
~ arr1

array([[ -9,  -3,  -2,  -7],
       [ -6, -10,  -2,  -9],
       [ -5,  -4,  -9,  -8]])

In [169]:
arr1|arr2

array([[ 8,  2,  7,  7],
       [ 7,  9,  5, 15],
       [12, 11, 15,  7]])

In [170]:
(arr1.shape,arr2.shape)

((3, 4), (3, 4))

In [171]:
(arr1.shape,arr2.T.shape)

((3, 4), (4, 3))

In [172]:
arr1>arr2

array([[False, False, False, False],
       [False,  True, False,  True],
       [False, False,  True,  True]])

In [173]:
arr1@arr2.T

array([[117, 111, 107],
       [121, 163, 152],
       [143, 137, 136]])

In [174]:
arr1.dot(arr2.T)

array([[117, 111, 107],
       [121, 163, 152],
       [143, 137, 136]])

### **NumPy String Function**

In [175]:
arr=np.array(['sudh','kumar'])
arr

array(['sudh', 'kumar'], dtype='<U5')

In [176]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [177]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [178]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

### **NumPy Mathematical Function**

In [179]:
arr1

array([[8, 2, 1, 6],
       [5, 9, 1, 8],
       [4, 3, 8, 7]])

In [180]:
np.sin(arr1)

array([[ 0.98935825,  0.90929743,  0.84147098, -0.2794155 ],
       [-0.95892427,  0.41211849,  0.84147098,  0.98935825],
       [-0.7568025 ,  0.14112001,  0.98935825,  0.6569866 ]])

In [181]:
np.cos(arr1)

array([[-0.14550003, -0.41614684,  0.54030231,  0.96017029],
       [ 0.28366219, -0.91113026,  0.54030231, -0.14550003],
       [-0.65364362, -0.9899925 , -0.14550003,  0.75390225]])

In [182]:
np.tan(arr1)

array([[-6.79971146, -2.18503986,  1.55740772, -0.29100619],
       [-3.38051501, -0.45231566,  1.55740772, -6.79971146],
       [ 1.15782128, -0.14254654, -6.79971146,  0.87144798]])

In [183]:
np.tan(np.deg2rad(arr1))

array([[0.14054083, 0.03492077, 0.01745506, 0.10510424],
       [0.08748866, 0.15838444, 0.01745506, 0.14054083],
       [0.06992681, 0.05240778, 0.14054083, 0.12278456]])

In [184]:
np.deg2rad(90)

1.5707963267948966

In [185]:
np.rad2deg(90)

5156.620156177409

In [186]:
radians = np.deg2rad(90)

In [187]:
result = np.tan(radians)

print(result)

1.633123935319537e+16


In [188]:
np.tanh(arr1)

array([[0.99999977, 0.96402758, 0.76159416, 0.99998771],
       [0.9999092 , 0.99999997, 0.76159416, 0.99999977],
       [0.9993293 , 0.99505475, 0.99999977, 0.99999834]])

In [189]:
np.log10(arr1)

array([[0.90308999, 0.30103   , 0.        , 0.77815125],
       [0.69897   , 0.95424251, 0.        , 0.90308999],
       [0.60205999, 0.47712125, 0.90308999, 0.84509804]])

In [190]:
np.exp(arr1)

array([[2.98095799e+03, 7.38905610e+00, 2.71828183e+00, 4.03428793e+02],
       [1.48413159e+02, 8.10308393e+03, 2.71828183e+00, 2.98095799e+03],
       [5.45981500e+01, 2.00855369e+01, 2.98095799e+03, 1.09663316e+03]])

In [191]:
np.sqrt(arr1)

array([[2.82842712, 1.41421356, 1.        , 2.44948974],
       [2.23606798, 3.        , 1.        , 2.82842712],
       [2.        , 1.73205081, 2.82842712, 2.64575131]])

In [192]:
np.power(arr1,2)

array([[64,  4,  1, 36],
       [25, 81,  1, 64],
       [16,  9, 64, 49]])

In [193]:
np.power(arr1,-2)

ValueError: Integers to negative integer powers are not allowed.

In [198]:
arr3 = arr1.copy().astype(float)
arr3

array([[8., 2., 1., 6.],
       [5., 9., 1., 8.],
       [4., 3., 8., 7.]])

In [199]:
np.power(arr3, -2)

array([[0.015625  , 0.25      , 1.        , 0.02777778],
       [0.04      , 0.01234568, 1.        , 0.015625  ],
       [0.0625    , 0.11111111, 0.015625  , 0.02040816]])

In [195]:
arr2 = np.array([2, 3, 4, 5], dtype=float)  # Convert to float

result = np.power(arr2, -2)

print(result)


[0.25       0.11111111 0.0625     0.04      ]


In [200]:
arr1.mean()

5.166666666666667

In [205]:
np.mean(arr1)

5.166666666666667

In [204]:
np.median(arr1)

5.5

In [208]:
np.std(arr1)

2.793842435706702

In [209]:
np.var(arr1)

7.805555555555556

In [210]:
np.min(arr1)

1

In [211]:
np.max(arr1)

9